<?php

namespace AppBundle\Repository;

/**
 * DependencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DependencyRepository extends \Doctrine\ORM\EntityRepository
{
}
