# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.packagist.client:
        class: AppBundle\Packagist\Client
        arguments: ["@buzz.browser"]
        public: true

    app.entity.package_repository:
        class: Doctrine\Common\Persistence\ObjectRepository
        factory:
            - "@doctrine"
            - "getRepository"
        arguments:
            - AppBundle\Entity\Package
        public: false

    app.provider.package.doctrine:
        class: AppBundle\Provider\Package\Doctrine
        arguments: ["@app.entity.package_repository"]
        public: false

    app.provider.package.factory:
        class: AppBundle\Provider\Package\Factory
        public: false

    app.provider.package.chain:
        class: AppBundle\Provider\Package\Chain
        arguments:
            - ["@app.provider.package.doctrine", "@app.provider.package.factory"]
        public: false

    app.provider.package.cache:
        class: AppBundle\Provider\Package\Cache
        arguments:
            - "@app.provider.package.chain"
        public: false

    app.provider.package:
        alias: app.provider.package.cache
        public: true

    buzz.browser:
        class: Buzz\Browser
        public: false